version: '3.8'

services:
  metrics:
    build:
      context: ../../../
      dockerfile: setup_docker/fs_metric_manager/Dockerfile
      args:
        my_arg: 1
    environment:
      - BACKEND_URI_PROD=http://backend_api:8001
      - DB_HOST=pg
      - DB_NAME=fs_metastore
      - DB_PASS=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - MLOPS_TEAMLEAD=someone
      - SCHEMA_NAME=mm_stable
    depends_on:
      pg:
        condition: service_healthy
      fsdb:
        condition: service_started
    command: uvicorn fs_metric_manager.server:app --host 0.0.0.0 --port 8003
    ports:
      - "8003:8003"