version: '3.8'

services:
  registry:
    build:
      context: ../../../
      dockerfile: setup_docker/fs_registry_api/Dockerfile
      args:
        my_arg: 1
    environment:
      - DB_HOST=pg
      - DB_NAME=fs_metastore
      - DB_PASS=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - MLOPS_TEAMLEAD=someone
      - SCHEMA_NAME=public
    depends_on:
      pg:
        condition: service_healthy
      fsdb:
        condition: service_started
    command: uvicorn fs_registry_api.server:app --host 0.0.0.0 --port 8002
    ports:
      - "8002:8002"