apiVersion: v1
kind: Service
metadata:
  name: fs-general-api
  namespace: fs-general-api-namespace # will be changed during deployment
  labels:
    app: fs-general-api
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: fs-general-api